"""
ml_physician_model.py
----------------------
ML component (Python / scikit-learn): predicts which physicians are
UNDER-PRESCRIBING a target therapy relative to their expected panel-adjusted
demand. This is a realistic ZS-style commercial analytics use case (HCP
segmentation for territory/call-plan targeting).

NOTE ON DATA: Physician-level prescribing behavior data is not available in
public datasets (it's proprietary/HIPAA-adjacent, typically licensed from
IQVIA/Symphony Health or provided directly by a pharma client). This module
therefore uses a REALISTIC SIMULATED physician panel dataset
(data/physician_data.csv, generated by src/generate_data.py) that mirrors the
feature set and relationships found in real commercial pharma engagements:
panel size, rep visit frequency, digital engagement, formulary access, peer
influence, and specialty/region.

Outputs:
  outputs/physician_model_metrics.json   - accuracy, precision, recall, F1, ROC-AUC
  outputs/physician_feature_importance.csv
  outputs/physician_predictions.csv      - per-physician latest-quarter risk scores
"""

import json
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score, roc_auc_score,
    confusion_matrix,
)

import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_PATH = os.path.join(BASE_DIR, "data", "physician_data.csv")
OUT_METRICS = os.path.join(BASE_DIR, "outputs", "physician_model_metrics.json")
OUT_IMPORTANCE = os.path.join(BASE_DIR, "outputs", "physician_feature_importance.csv")
OUT_PREDICTIONS = os.path.join(BASE_DIR, "outputs", "physician_predictions.csv")

NUMERIC_FEATURES = [
    "panel_size", "years_experience", "digital_engagement_score",
    "rep_visits_per_quarter", "formulary_access_pct", "peer_influence_score",
]
CATEGORICAL_FEATURES = ["region", "specialty"]
TARGET = "under_prescriber"


def build_pipeline() -> Pipeline:
    preprocess = ColumnTransformer([
        ("num", "passthrough", NUMERIC_FEATURES),
        ("cat", OneHotEncoder(handle_unknown="ignore"), CATEGORICAL_FEATURES),
    ])
    clf = GradientBoostingClassifier(
        n_estimators=200, max_depth=3, learning_rate=0.08, random_state=42,
    )
    return Pipeline([("preprocess", preprocess), ("clf", clf)])


def run():
    df = pd.read_csv(DATA_PATH)

    X = df[NUMERIC_FEATURES + CATEGORICAL_FEATURES]
    y = df[TARGET]

    # Split by physician_id so the same physician's quarters don't leak across train/test
    physician_ids = df["physician_id"].unique()
    train_ids, test_ids = train_test_split(physician_ids, test_size=0.25, random_state=42)
    train_mask = df["physician_id"].isin(train_ids)
    test_mask = df["physician_id"].isin(test_ids)

    X_train, y_train = X[train_mask], y[train_mask]
    X_test, y_test = X[test_mask], y[test_mask]

    pipe = build_pipeline()
    pipe.fit(X_train, y_train)

    y_pred = pipe.predict(X_test)
    y_proba = pipe.predict_proba(X_test)[:, 1]

    metrics = {
        "accuracy": round(accuracy_score(y_test, y_pred), 4),
        "precision": round(precision_score(y_test, y_pred), 4),
        "recall": round(recall_score(y_test, y_pred), 4),
        "f1_score": round(f1_score(y_test, y_pred), 4),
        "roc_auc": round(roc_auc_score(y_test, y_proba), 4),
        "n_train": int(train_mask.sum()),
        "n_test": int(test_mask.sum()),
        "base_rate_under_prescriber": round(float(y.mean()), 4),
    }
    cm = confusion_matrix(y_test, y_pred)
    metrics["confusion_matrix"] = {"tn": int(cm[0, 0]), "fp": int(cm[0, 1]),
                                    "fn": int(cm[1, 0]), "tp": int(cm[1, 1])}

    with open(OUT_METRICS, "w") as f:
        json.dump(metrics, f, indent=2)

    # Feature importances (map one-hot cols back to readable names)
    ohe = pipe.named_steps["preprocess"].named_transformers_["cat"]
    cat_names = list(ohe.get_feature_names_out(CATEGORICAL_FEATURES))
    all_feature_names = NUMERIC_FEATURES + cat_names
    importances = pipe.named_steps["clf"].feature_importances_
    imp_df = pd.DataFrame({"feature": all_feature_names, "importance": importances})
    imp_df = imp_df.sort_values("importance", ascending=False)
    imp_df.to_csv(OUT_IMPORTANCE, index=False)

    # Score most recent quarter for every physician -> risk list for territory targeting
    latest_q = df["quarter"].max()
    latest = df[df["quarter"] == latest_q].copy()
    latest["under_prescriber_risk_score"] = pipe.predict_proba(
        latest[NUMERIC_FEATURES + CATEGORICAL_FEATURES]
    )[:, 1]
    latest_out = latest[[
        "physician_id", "region", "specialty", "panel_size",
        "expected_scripts", "actual_scripts", "under_prescriber_risk_score",
    ]].sort_values("under_prescriber_risk_score", ascending=False)
    latest_out.to_csv(OUT_PREDICTIONS, index=False)

    print("=== Physician Under-Prescriber Classification Model ===")
    print(json.dumps(metrics, indent=2))
    print("\nTop 5 predictive features:")
    print(imp_df.head(5).to_string(index=False))
    print(f"\nHighest-risk physicians for {latest_q} (top 5 for rep targeting):")
    print(latest_out.head(5).to_string(index=False))


if __name__ == "__main__":
    run()
